### ISSUE TITLE
구조체 변수 정의

### ISSUE THREAD

**Issue by gusanr7489** [gusanr7489/LateReturnDorm#1]
지금 저희가 필요한 변수들 
이름 
학번 
호실

늦귀 사유
머무르는 장소
복귀 예상 시간
복귀 시간

이렇게 있는데 더 필요한 변수 있을까요? 
그리고 저희 학번이나 호실, 시간은 어떤 변수 타입으로 정의할까요?

**Comment by gusanr7489** [comment]
참 저희 메뉴 함수도 추가할 수 있어요.

**Comment by systec24** [comment]
늦은귀관 후 체온측정도 있긴한데 이건 기숙사 별로 달라서 자율적으로 하면 될 것 같고 학번이랑 호실 시간 전부다 정수형으로 정의하면 될 거 같아요. 메뉴함수는 그럼 제가 edit해서 추가해놓을게요.

**Comment by gusanr7489** [comment]
이름 - string
학번 - int  or  string
호실 - int  or  string
늦귀 사유 - string
머무르는 장소 - string
복귀 예상 시간 - int  or  string
복귀 시간 - int  or  string

**Comment by gusanr7489** [comment]
정수로 하게 되면 별 문제는 없겠죠?
시간 관련 함수는 int 값으로 나오나요?

**Comment by systec24** [comment]
시간은 함수구현 알아보니까 string형태로 하는게 나을 것 같아요

**Comment by gusanr7489** [comment]
이름 - string
학번 - int
호실 - int
늦귀 사유 - string
머무르는 장소 - string
복귀 예상 시간 - string
복귀 시간 - string

**Comment by gusanr7489** [comment]
더 필요한 변수 없겠죠?

**Comment by systec24** [comment]
넵! 괜찮은 것 같습니다

**Comment by gusanr7489** [comment]
아주 좋습니다ㅏㅏ굿굿굿
